"""
This type stub file was generated by pyright.
"""

from typing import Literal, Required, TypedDict

Sortfield = Literal["id", "name", "mindate", "maxdate", "datacoverage", ""]
Sortorder = Literal["asc", "desc"]
Units = Literal["standard", "metric", ""]
class DatasetsParameters(TypedDict, total=False):
    datatypeid: str
    locationid: str
    stationid: str
    startdate: str
    enddate: str
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    ...


class DatacategoriesParameters(TypedDict, total=False):
    datasetid: str
    locationid: str
    stationid: str
    startdate: str
    enddate: str
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    ...


class DatatypesParameters(TypedDict, total=False):
    datasetid: str
    locationid: str
    stationid: str
    datacategoryid: str
    startdate: str
    enddate: str
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    ...


class LocationcategoriesParameters(TypedDict, total=False):
    datasetid: str
    startdate: str
    enddate: str
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    ...


class LocationsParameters(TypedDict, total=False):
    datasetid: str
    locationcategoryid: str
    datacategoryid: str
    startdate: str
    enddate: str
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    ...


class StationsParameters(TypedDict, total=False):
    datasetid: str
    locationid: str
    datacategoryid: str
    datatypeid: str
    extent: str
    startdate: str
    enddate: str
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    ...


class DataParameters(TypedDict, total=False):
    datasetid: Required[str]
    datatypeid: str
    locationid: str
    stationid: str
    startdate: Required[str]
    enddate: Required[str]
    units: Units
    sortfield: Sortfield
    sortorder: Sortorder
    limit: int
    offset: int
    includemetadata: bool
    ...


AnyParameter = (DatasetsParameters | DatacategoriesParameters | DatatypesParameters | LocationcategoriesParameters | LocationsParameters | StationsParameters | DataParameters)
